type Mutation {
  createAlbum(title: String!, userId: ID!): Album
  updateAlbum(id: ID!, title: String!, userId: ID!): Album
  deleteAlbum(id: ID!): Album
  createComment(
    name: String!
    email: String!
    body: String!
    postId: ID!
  ): Comment
  updateComment(
    id: ID!
    name: String!
    email: String!
    body: String!
    postId: ID!
  ): Comment
  deleteComment(id: ID!): Comment
  createPhoto(
    title: String!
    url: String!
    thumbnailUrl: String!
    albumId: ID!
  ): Photo
  updatePhoto(
    id: ID!
    title: String!
    url: String!
    thumbnailUrl: String!
    albumId: ID!
  ): Photo
  deletePhoto(id: ID!): Photo
  createPost(title: String!, body: String!, userId: ID!): Post
  updatePost(id: ID!, title: String!, body: String!, userId: ID!): Post
  deletePost(id: ID!): Post
  createTodo(title: String!, completed: Boolean!, userId: ID!): Todo
  updateTodo(id: ID!, title: String!, completed: Boolean!, userId: ID!): Todo
  deleteTodo(id: ID!): Todo
  createUser(
    name: String!
    username: String!
    email: String!
    phone: String!
    address: AddressInput!
  ): User
  updateUser(
    id: ID!
    name: String!
    username: String!
    email: String!
    phone: String!
    address: AddressInput!
  ): User
  deleteUser(id: ID!): User
}
