type Mutation {
  putAlbum(album: AlbumInput!): Album
  deleteAlbum(id: ID!): Boolean!
  putComment(comment: CommentInput!): Comment
  deleteComment(id: ID!): Boolean!
  putPhoto(photo: PhotoInput!): Photo
  deletePhoto(id: ID!): Boolean!
  putPost(post: PostInput!): Post
  deletePost(id: ID!): Boolean!
  putTodo(todo: TodoInput!): Todo
  deleteTodo(id: ID!): Boolean!
  putUser(user: UserInput!): User
  deleteUser(id: ID!): Boolean!
}
